meta_product_name: "Uziic"
meta_title: "Uziic - be a part of your city's sound "
meta_description: "discover and share, artists and bands around your city"
meta_image: "logo.png" # should exist in `app/assets/images/`


